# Generated by Django 3.2 on 2021-05-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AddField(
            model_name='user',
            name='emial',
            field=models.EmailField(default='test@django.com', max_length=128, verbose_name='이메일'),
            preserve_default=False,
        ),
    ]
